### ISSUE TITLE
Crash after Reboot

### ISSUE THREAD

**Issue by KonradStuewe** [Carbon-OS/CarbonOS#6]
Version: 1.0.5.3
Error: os:20: attempt to perform arithmetic on string
What i did to cause this error: Install OS using "pastebin run 5BsVEnu3" > Reboot > Error

**Comment by jtrent238** [comment]
![](http://puu.sh/vBdxe/93943b6009.jpg)

**Comment by Ashton08Real** [comment]
i am getting this error too try running it on
1.Command pc
2.normal pc

**Comment by CoolMan119** [comment]
CarbonOS is no longer supported sadly. However, a new OS is on it's way called Craftix.

**Comment by jtrent238** [comment]
:cry:
